Describe package modifications in Readme
chaotic-aur/packages pull request #2938
Opened 2023-12-03 00:44 UTC by xiota

Add section to describe package modifications.  Origin of Chaotic AUR seems to be to build packages from AUR without modification.  However, doing so is not always practical or possible.  New section clarifies that packages are not necessarily built without change.

Also, some minor updates to "packages we have already built", like adding link to separate KDE-git repo.

2023-12-03 02:00 UTC, Technetium1 requested changes
Fantastic!

2023-12-03 03:05 UTC, xiota commented on README.md
> +- Common errors and poor packaging practices are automatically corrected.
I wasn't sure if directing everyone to the toolbox/interfere repos is necessary or desirable.  While they're not secret, unnecessary exposure could cause problems.

2023-12-03 08:28 UTC, dr460nf1r3 commented on README.md
> +- Common errors and poor packaging practices are automatically corrected.
What kind of problems are you expecting?

2023-12-03 08:29 UTC, dr460nf1r3 commented on README.md
> +Chaotic-AUR contains a metapackage, `chaotic-kf5-dummy`.  This is a *temporary* workaround to allow some packages to continue functioning while upstream renames the KF5 packages.  Eventually the dumm
Sounds great, imo! Not only does this serve as documentation for maintainers, it also increases transparency.

2023-12-03 09:39 UTC, xiota commented on README.md
> +- Common errors and poor packaging practices are automatically corrected.
Could make easier for maintainers to construct packages to intentionally break toolbox or bypass the generic interfere.  I suppose any maintainer caught trying to harm the servers or users could be banned and have all of their packages forked or dropped.

2023-12-04 07:15 UTC, xiota commented on README.md
> +- Some packages are manually adjusted (interfere).
Added in revision.

2023-12-04 07:16 UTC, xiota commented on README.md
> +Chaotic-AUR contains a metapackage, `chaotic-kf5-dummy`.  This is a *temporary* workaround to allow some packages to continue functioning while upstream renames the KF5 packages.  Eventually the dumm
Added in revision.

2023-12-04 18:37 UTC, merged